title: RDF WIKI
description: Wiki for RDF Lab @ FIU
theme: just-the-docs

color_scheme: dark

nav_order: 2

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
